// app/layout.tsx

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import your Navbar and Footer components
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Place the Navbar at the top */}
        <Navbar />

        {/* The children prop will render the content of the current page */}
        <main>{children}</main>

        {/* Place the Footer at the bottom */}
        <Footer />
      </body>
    </html>
  );
}